### ISSUE TITLE
If set expiration date is before current date, checkout page redirects to level page

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-set-expiration-dates#10]
Could create a notice to admins the level expiration date has passed, and that members will not able to checkout.

**Comment by pbrocks** [comment]
@greathmaster How about a welcome page like this https://github.com/pbrocks/pmpro-set-expiration-dates/tree/dev-welcome-page

**Comment by andrewlimaza** [comment]
Or we should hide the level from the levels array :)

**Comment by andrewlimaza** [comment]
and have a notice to admins.

**Comment by andrewlimaza** [comment]
Working this into the next release.
![Screen Shot 2020-09-14 at 11 08 26](https://user-images.githubusercontent.com/12629136/93066748-a8673300-f67a-11ea-9f20-162ee2b0dc2d.png)
