### ISSUE TITLE
PMPro With WooCommerce Doesn't Fire Expiration Date

### ISSUE THREAD

**Issue by Iteratix** [strangerstudios/pmpro-set-expiration-dates#2]
Hi there,

I wanted to check to see if this plugin is supported with PMPro WooCommerce integration, as it doesn't seem the fixed expiration date is pushed to the membership with this particular configuration.

Paid Memberships Pro 1.7.14.2 
PMPro WooCommerce 1.2.7

**Comment by LMNTL** [comment]
It looks like `pmprosed_pmpro_checkout_level`, would need to be hooked into 'pmprowoo_checkout_level' to make the two plugins compatible, but this isn't currently possible because `pmprosed_pmpro_checkout_level` treats the level as an object and 'pmprowoo_checkout_level' only accepts arrays.

**Comment by avikatzav** [comment]
There is any snippet to solve that?

**Comment by andrewlimaza** [comment]
Here is a code snippet - https://gist.github.com/andrewlimaza/938056a3997c38075d3e858d3ada528b
