### ISSUE TITLE
The hint in level settings is incorrect --"Membership Expiration" is not required.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-set-expiration-dates#20]
The "Note: You must also set an expiration date above (e.g. 1 Year) which will be overwritten by the value below." hint is wrong. "Membership Expiration" is not required for the set expiration date to work.

https://github.com/strangerstudios/pmpro-set-expiration-dates/blob/a0acaf2a50d33a70ea44a62311462aa36ae71c55/pmpro-set-expiration-dates.php#L25-L26

**Comment by tbnv** [comment]
"Membership Expiration" is indeed required. And from what I see, when I don't set an expiration (e.g. 1 year), the resulting expiration is forever.

**Comment by eighty20results** [comment]
I second that setting the Membership Expiration settings are indeed required with this add-on active. Without it, the logic fails in `pmpro_getLevelAtCheckout()` and in the PMPro WooCommerce add-on (neither will include/set an end date for the level even if the "Expiration Date" setting contains a value)

**Comment by messica** [comment]
Thanks for the feedback. I'm closing this.
