### ISSUE TITLE
wrong expiration date for new user

### ISSUE THREAD

**Issue by dragonjhlee** [strangerstudios/pmpro-set-expiration-dates#22]
when the new user registered to our website, the expiration date gets random value although I set it as the 1 year from current date; the year difference is more than 15 years by default.
(i.e. current date: 2019/4/23  -> expiration date : 2035/3/20) 
This happening even without this add-on (I never installed this add-on)
![Capture](https://user-images.githubusercontent.com/47336473/56588323-1ce69100-65b1-11e9-99d5-f8dbbcd3d6c8.PNG)
.

I already checked the system date of server, SQL and wordpress but it is all good.

Would you help me to resolve this issue?

**Comment by ideadude** [comment]
Do you have any idea how to recreate this? Does it happen for every checkout, level, user, etc.

Note that expirations are "extended" when someone checks out repeatedly, e.g. when testing the checkout with the same user. So if you have a level set to expire in 1 year and checkout 15 times, it will push it back 1 year, 15 times and end up with something like this.

For faster support for specific installations, use our paid member support here https://www.paidmembershipspro.com/pricing/

**Comment by dragonjhlee** [comment]
Thanks @ideadude 

It is happening every time from that above time-line in a production, not a testing environment. And I do not think they signed up repeatedly, meaning they had to pay multiple times, no way....

Do you think the upgrade of PMpro will resolve this issue? Since the recent PMpro is not compatible with WP 5.1.1, I did not upgrade it yet to minimize the potential risk.

**Comment by ideadude** [comment]
It's been a while, but upgrading PMPro is a good idea. We are compatible with the latest version of WordPress. We don't always get around to updating those tested up to dates until we push a general update to the plugin, but if a version of WP has been out for a few days, PMPro is compatible with it. We work on the latest version of WP and test on the release candidates/etc to make sure things don't break when people update.

**Comment by dragonjhlee** [comment]
Hi @ideadude ,

I upgraded to the latest version but the issue still persists. I think this happened due to the Paypal IPN issue. But it is working fine when the auto renewal happens though within Paypal. 

I turned on the debug mode of Paypal IPN as True to dig into it, but never received any msg for new user signed up. It seems like Paypal IPN msg never gets delivered to our page after the successful payment proceeded so it keeps trying till about 15 times, and it increases 1 year every trial.

Somehow there is an issue to receive back the Paypal IPN msg gets delivered to our page since Auto renewal from Paypal working fine. 

I think the simple solution would be to stop adding the 1 year (expiration period) if the user already gets created for the first time (i.e. all payment goes through successfully). But I do not know how to filter/catch this event.  

Thanks for your help in advance

**Comment by andrewlimaza** [comment]
Hi @dragonjhlee did you manage to resolve this issue? I would like to look into this further. Can you tell me more about your setup?

Are you using recurring levels and an expiration date?

**Comment by andrewlimaza** [comment]
You mentioned in your initial post: 

the year difference is more than 15 years by default.
(i.e. current date: 2019/4/23 -> expiration date : 2035/3/20)
This happening even without this add-on (I never installed this add-on)

To clarify, you never installed the Set Expiration Date Add On?

**Comment by dragonjhlee** [comment]
Hi @andrewlimaza 

Yes, we are using recurring levels with a different expiration date. And also no I never installed the Set Expiration date add on.

Best,
Jun

**Comment by andrewlimaza** [comment]
Thanks for this Jun, please can you open a support ticket on www.paidmembershipspro.com - This repository is for bugs/feature requests for the Set Expiration Date Add On.

I will close this ticket, someone from our team will assist you further. Thank you for understanding.
