### ISSUE TITLE
Set Expiration Date is a day early for some users.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-set-expiration-dates#36]
**Describe the bug**
Sometimes member's end date is set a day early.
EXAMPLE:   expiration date set to 2021-12-31, after users check out Expiration date set to 2021-12-30.

Can be caused by this calculation:
https://github.com/strangerstudios/pmpro-set-expiration-dates/blob/90bab99b59fd2a1885528f2f2db46ea1be68eb33/pmpro-set-expiration-dates.php#L183-L218

**Screenshots**
![wrong-date](https://user-images.githubusercontent.com/8083630/119540510-21af3d80-bd53-11eb-9746-0a0ebecc9de3.png)

**Expected behavior**
Set Expiration Date should take into account local timezone.

**Comment by andrewlimaza** [comment]
This may have been an issue with a specific payment gateway. I've just tested this and unable to replicate.

Could you tell me if you're still facing this issue and share details about your setup (payment gateway and Set Expiration Date Settings is it hardcoded or using variables like Y1-12-31)?

**Comment by andrewlimaza** [comment]
This has been resolved.
